spring:
  application:
   name: auraoj-backend
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: ${DB_PASSWORD}
    url: jdbc:postgresql://localhost:5432/auraoj?stringtype=unspecified&currentSchema=public&sslmode=disable&connectTimeout=30

  mvc:
    static-path-pattern: /**

mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  type-aliases-package: com.zhy.auraojbackend.model.entity
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

logging:
  level:
    org:
      springframework:
        boot:
          autoconfigure: ERROR

############## Sa-Token 配置 ##############
sa-token:
  # token 名称（同时也是 cookie 名称）
  token-name: satoken
  # token 有效期（单位：秒） 默认30天，-1 代表永久有效
  timeout: 2592000
  # token 最低活跃频率（单位：秒），如果 token 超过此时间没有访问系统就会被冻结，默认-1 代表不限制，永不冻结
  active-timeout: -1
  # 是否允许同一账号多地同时登录 （为 true 时允许一起登录, 为 false 时新登录挤掉旧登录）
  is-concurrent: false
  # 在多人登录同一账号时，是否共用一个 token （为 true 时所有登录共用一个 token, 为 false 时每次登录新建一个 token）
  is-share: false
  # token 风格（默认可取值：uuid、simple-uuid、random-32、random-64、random-128、tik）
  token-style: uuid
  # 是否输出操作日志  
  is-log: true

############## SpringDoc / Swagger 配置 ##############
springdoc:
  api-docs:
    enabled: true # 开启 API 文档生成
    path: /v3/api-docs
  packages-to-scan: com.zhy.auraojbackend.controller
  default-flat-param-object: true
  group-configs:
    - group: default
      paths-to-match: /**
# Knife4j 增强配置
knife4j:
  enable: true # 开启 Knife4j
  setting:
    language: zh_cn # 设置语言为中文
    # 生产环境建议关闭文档，或通过安全策略控制
    # production: true
  basic:
    enable: false # 如果不需要账号密码认证，设为 false

# minio 配置


minio:
  endpoint: ${MINIO_ENDPOINT}
  access-key: ${MINIO_AK}
  access-secret: ${MINIO_SK}
  bucket-name: auraoj
  secure: false